/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_att_aro_pcap_NetmonAdapter */

#ifndef _Included_com_att_aro_pcap_NetmonAdapter
#define _Included_com_att_aro_pcap_NetmonAdapter
#ifdef __cplusplus
extern "C" {
#endif
#undef com_att_aro_pcap_NetmonAdapter_NETMON_ERROR
#define com_att_aro_pcap_NetmonAdapter_NETMON_ERROR -100L
#undef com_att_aro_pcap_NetmonAdapter_NETMON_TRACE_FILE_LOAD_ERROR
#define com_att_aro_pcap_NetmonAdapter_NETMON_TRACE_FILE_LOAD_ERROR -101L
#undef com_att_aro_pcap_NetmonAdapter_NETMON_PARSING_SUCCESS
#define com_att_aro_pcap_NetmonAdapter_NETMON_PARSING_SUCCESS 0L
/*
 * Class:     com_att_aro_pcap_NetmonAdapter
 * Method:    parseTrace
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_att_aro_pcap_NetmonAdapter_parseTrace
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
