/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_att_aro_pcap_AROCryptoAdapter */

#ifndef _Included_com_att_aro_pcap_AROCryptoAdapter
#define _Included_com_att_aro_pcap_AROCryptoAdapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_att_aro_pcap_AROCryptoAdapter
 * Method:    parseTrace
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_att_aro_pcap_AROCryptoAdapter_ReadSSLKeys
  (JNIEnv *, jobject, jstring);

JNIEXPORT jint JNICALL Java_com_att_aro_pcap_AROCryptoAdapter_tlsprf
	(JNIEnv *env, jobject obj, jbyteArray preMaster, jint preMasterLen, jstring label, jbyteArray random, jint randomLen, jbyteArray master, jint masterSecretLen);

JNIEXPORT jint JNICALL Java_com_att_aro_pcap_AROCryptoAdapter_cryptocipherinit
	(JNIEnv *env, jobject obj, jint alg, jbyteArray temp1, jbyteArray temp2, jint key_material, jint bClient);

JNIEXPORT void JNICALL Java_com_att_aro_pcap_AROCryptoAdapter_cryptocipherdeinit
	(JNIEnv *env, jobject obj, jint objectType);

JNIEXPORT void JNICALL Java_com_att_aro_pcap_AROCryptoAdapter_setcryptociphernull
	(JNIEnv *env, jobject obj, jint objectType, jint bClient);

JNIEXPORT jint JNICALL Java_com_att_aro_pcap_AROCryptoAdapter_cryptocipherdecrypt
	(JNIEnv *env, jobject obj, jint pCipher, jbyteArray enc, jbyteArray _plain, jint enclength, jint objectType);

JNIEXPORT void JNICALL Java_com_att_aro_pcap_AROCryptoAdapter_copycryptocipher
	(JNIEnv *env, jobject obj, jint from, jint to);

JNIEXPORT jint JNICALL Java_com_att_aro_pcap_AROCryptoAdapter_cryptohashInitUpdateFinish(
	JNIEnv *env, jobject obj, jint dir, jint hash_alg, jbyteArray keyBlock, jint hash_size, jint recType, jint payloadLen, jbyteArray plain, jbyteArray seqNum);

#ifdef __cplusplus
}
#endif
#endif
