/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_att_aro_pcap_PCapAdapter */

#ifndef _Included_com_att_aro_pcap_PCapAdapter
#define _Included_com_att_aro_pcap_PCapAdapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_att_aro_pcap_PCapAdapter
 * Method:    ping
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_att_aro_pcap_PCapAdapter_ping
  (JNIEnv *, jclass);

/*
 * Class:     com_att_aro_pcap_PCapAdapter
 * Method:    loopPacket
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_att_aro_pcap_PCapAdapter_loopPacket
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
