package com.att.aro.core.peripheral.impl;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

import java.io.IOException;
import java.util.Date;
import java.util.List;

import org.junit.Before;
import org.junit.Test;
import org.mockito.Mockito;

import com.att.aro.core.BaseTest;
import com.att.aro.core.fileio.IFileManager;
import com.att.aro.core.packetanalysis.pojo.TraceDataConst;
import com.att.aro.core.peripheral.IWakelockInfoReader;
import com.att.aro.core.peripheral.pojo.WakelockInfo;
import com.att.aro.core.util.Util;

public class WakelockInfoReaderImplTest extends BaseTest {

	WakelockInfoReaderImpl traceDataReader;

	private IFileManager filereader;
	private String traceFolder = "traceFolder";

	@Before
	public void setup() {
		filereader = Mockito.mock(IFileManager.class);
		traceDataReader = (WakelockInfoReaderImpl)context.getBean(IWakelockInfoReader.class);

		traceDataReader.setFileReader(filereader);
	}

	@Test
	public void readData() throws IOException {
		Date traceDateTime = new Date((long)1412161675045.0);
		double dumpsysEpochTimestamp = (new Date((long)1.412361724E12)).getTime();
		
		List<WakelockInfo> wakelockInfos = null;
		
		String filepath = "" + Util.FILE_SEPARATOR + TraceDataConst.FileName.BATTERYINFO_FILE;
		Mockito.when(filereader.fileExist(filepath)).thenReturn(true);
		Mockito.when(filereader.readAllLine(Mockito.anyString())).thenReturn(getMockedFileData());
		traceDataReader.setFileReader(filereader);
		wakelockInfos = traceDataReader.readData("", "2.2", dumpsysEpochTimestamp, traceDateTime);
		
		
		wakelockInfos = traceDataReader.readData("", "4.2", dumpsysEpochTimestamp, traceDateTime);

		assertEquals(7, wakelockInfos.size(),0);

	}

	@Test
	public void readData_Exception_readAllLine() throws IOException {
		Date traceDateTime = new Date((long)1412161675045.0);
		double dumpsysEpochTimestamp = (new Date((long)1.412361724E12)).getTime();
		Mockito.when(filereader.fileExist(Mockito.anyString())).thenReturn(true);
		Mockito.when(filereader.readAllLine(Mockito.anyString())).thenThrow(new IOException("Exception_readAllLine"));

		List<WakelockInfo> wakelockInfos = traceDataReader.readData("", "2.2", dumpsysEpochTimestamp, traceDateTime);
		assertTrue(wakelockInfos.size() == 0);

	}


	/*
	 * batteryinfo_dump
	 */
	private String[] getMockedFileData() {
		return new String[] {
		     "Battery History:"
			,"      -17h55m35s224ms 100 6010f202 status=not-charging health=good plug=none temp=301 volt=4171 +screen +wake_lock +sensor brightness=medium phone_state=emergency data_conn=other"
			,"      -17h53m34s962ms 100 6010f202 temp=288"
			,"      -17h48m34s160ms 100 6010f202 temp=277"
			,"      -17h45m34s917ms 100 2000f202 -screen -wake_lock"
			,"      -17h45m34s890ms 100 0000f202 -sensor"
			,"      -17h42m54s185ms 100 0000f202 temp=262"
			,"      -16h45m48s182ms 100 4100f202 +wifi_scan_lock +wake_lock"
			,"      -16h45m48s094ms 100 0000f202 -wifi_scan_lock -wake_lock"
			,"      -16h45m03s896ms 100 0000f202 temp=246"
			,"      -15h45m02s938ms 100 0000f202 temp=226"
			,"      -14h45m03s118ms 100 0000f202 volt=4141"
			,"      -13h45m03s125ms 100 0000f202 temp=207"
			,"      -11h45m03s105ms 100 0000f202 temp=196"
			,"      -11h41m04s166ms 100 0000f202"
			,"      -10h45m02s931ms 099 0000f202"
			,"       -9h45m02s979ms 097 0000f202"
			,"       -8h45m03s166ms 096 0000f202 volt=4118"
			,"       -7h45m03s104ms 095 0000f202"
			,"       -6h45m02s924ms 094 0000f202"
			,"       -5h45m03s097ms 093 0000f202 temp=180"
			,"       -4h50m43s047ms 093 4100f202 +wifi_scan_lock +wake_lock"
			,"       -4h50m42s994ms 093 0000f202 -wifi_scan_lock -wake_lock"
			,"       -4h47m45s677ms 093 0000f202"
			,"       -4h45m03s113ms 093 0000f202 volt=4091"
			,"       -4h27m54s175ms 093 0000f202"
			,"       -3h45m03s132ms 092 0000f202"
			,"       -1h45m03s064ms 091 0000f202 temp=166"
			,"         -45m02s947ms 091 0000f202 temp=222"
			,"         -14m30s794ms 091 6018f242 status=charging plug=usb temp=226 volt=4078 +plugged +screen +wake_lock +sensor signal_strength=great"
			,"         -13m30s750ms 092 6018f242 temp=236 volt=4177"
			,"         -11m30s433ms 092 6018f242 temp=246"
			,"         -10m30s270ms 093 6018f242"
			,"          -8m29s946ms 093 6018f242 temp=256"
			,"          -7m29s796ms 093 6018f242 volt=4198"
			,"          -6m29s636ms 094 6018f242"
			,"          -4m29s313ms 094 6018f242 temp=267"
			,"          -2m28s992ms 095 6018f242"
			,"            -58s325ms 095 641af242 +wifi +wifi_running"
			,"            -49s414ms 095 651af242 +wifi_scan_lock"
			,"            -45s056ms 095 641af242 -wifi_scan_lock"
			,"            -28s682ms 095 641af242 temp=279"
			,"            -14s846ms 095 651af242 +wifi_scan_lock"
			,"            -12s450ms 095 641af242 -wifi_scan_lock"
			,""
			,"Per-PID Stats:"
			,"  PID 454 wake time: +27s135ms"
			,"  PID 7706 wake time: +1s265ms"
			,"  PID 802 wake time: +259ms"
			,"  PID 834 wake time: +37ms"
			,"  PID 948 wake time: +8s613ms"
			,"  PID 1316 wake time: +57ms"
			,"  PID 454 wake time: +10s331ms"
			,"  PID 873 wake time: +422ms"
			,""
			,"Statistics since last charge:"
			,"  System starts: 0, currently on battery: false"
			,"  Time on battery: 17h 41m 4s 437ms (2.8%) realtime, 11m 43s 232ms (0.0%) uptime"
			,"  Total run time: 26d 1h 2m 23s 902ms realtime, 5h 46m 46s 15ms uptime, "
			,"  Screen on: 10m 0s 307ms (0.9%), Input events: 0, Active phone call: 0ms (0.0%)"
			,"  Screen brightnesses: medium 10m 0s 307ms (100.0%)"
			,"  Kernel Wake lock \"qmi_564\": 67ms  (101 times) realtime"
			,"  Kernel Wake lock \"PowerManagerService\": 1m 23s 705ms  (233 times) realtime"
			,"  Kernel Wake lock \"alarm_rtc\": 27s 226ms  (134 times) realtime"
			,"  Kernel Wake lock \"smdcntl7\": 1ms  (0 times) realtime"
			,"  Kernel Wake lock \"htc_battery_8960\": 3s 480ms  (28 times) realtime"
			,"  Kernel Wake lock \"KeyEvents\": 5ms  (141 times) realtime"
			,"  Kernel Wake lock \"smdcntl0\": 16s 889ms  (85 times) realtime"
			,"  Kernel Wake lock \"smdcntl4\": 1ms  (0 times) realtime"
			,"  Kernel Wake lock \"qmuxd_500\": 18ms  (101 times) realtime"
			,"  Kernel Wake lock \"HS_PMIC\": 1ms  (0 times) realtime"
			,"  Kernel Wake lock \"power-supply\": 152ms  (29 times) realtime"
			,"  Kernel Wake lock \"radio-interface\": 2s 39ms  (2 times) realtime"
			,"  Kernel Wake lock \"smdcntl3\": 1ms  (0 times) realtime"
			,"  Kernel Wake lock \"display_mdp_idle\": 639ms  (92 times) realtime"
			,"  Kernel Wake lock \"HS_MGR\": 1ms  (0 times) realtime"
			,"  Kernel Wake lock \"vbus_lock\": 96ms  (1 times) realtime"
			,"  Kernel Wake lock \"event4-454\": 8ms  (4 times) realtime"
			,"  Kernel Wake lock \"kgsl-3d0\": 8s 334ms  (480 times) realtime"
			,"  Kernel Wake lock \"alarm\": 8s 537ms  (236 times) realtime"
			,"  Kernel Wake lock \"kgsl-2d0\": 2ms  (1 times) realtime"
			,"  Kernel Wake lock \"smdcntl6\": 1ms  (0 times) realtime"
			,"  Kernel Wake lock \"pm8921_eoc\": 6s 47ms  (0 times) realtime"
			,"  Kernel Wake lock \"smdcntl2\": 1ms  (0 times) realtime"
			,"  Kernel Wake lock \"pm8xxx_adc_wakelock\": 1s 632ms  (476 times) realtime"
			,"  Kernel Wake lock \"diagchar\": 1ms  (0 times) realtime"
			,"  Kernel Wake lock \"msm_ipc_read\": 85ms  (5 times) realtime"
			,"  Kernel Wake lock \"mmc0_detect\": 1ms  (0 times) realtime"
			,"  Kernel Wake lock \"msm_otg\": 67ms  (1 times) realtime"
			,"  Kernel Wake lock \"kgsl-2d1\": 2ms  (1 times) realtime"
			,"  Kernel Wake lock \"proximity\": 8s 117ms  (1 times) realtime"
			,"  Kernel Wake lock \"smdcntl1\": 1ms  (0 times) realtime"
			,"  Kernel Wake lock \"main\": 10m 0s 594ms  (0 times) realtime"
			,"  Kernel Wake lock \"smdcntl5\": 1ms  (0 times) realtime"
			,"  Kernel Wake lock \"port_list\": 2ms  (336 times) realtime"
			,"  Kernel Wake lock \"pm8921_unplug_ovp_fet_open_wake_lock\": 1ms  (1 times) realtime"
			,"  Total received: 0B, Total sent: 0B"
			,"  Total full wakelock time: 162ms , Total partial waklock time: 1m 23s 732ms "
			,"  Signal levels: No activity"
			,"  Signal scanning time: 0ms "
			,"  Radio types: other 17h 41m 4s 437ms (100.0%) 0x"
			,"  Radio data uptime when unplugged: 0 ms"
			,"  Wifi on: 0ms (0.0%), Wifi running: 0ms (0.0%), Bluetooth on: 0ms (0.0%)"
			," "
			,"  Device battery use since last full charge"
			,"    Amount discharged (lower bound): 8"
			,"    Amount discharged (upper bound): 9"
			,"    Amount discharged while screen on: 0"
			,"    Amount discharged while screen off: 9"
			," "
			,"  #0:"
			,"    Proc /init:"
			,"      CPU: 60ms usr + 920ms krn"
			,"    Proc ksoftirqd/0:"
			,"      CPU: 0ms usr + 210ms krn"
			,"    Proc vold:"
			,"      CPU: 10ms usr + 120ms krn"
			,"    Proc flush-0:17:"
			,"      CPU: 10ms usr + 0ms krn"
			,"    Proc flush-0:18:"
			,"      CPU: 10ms usr + 0ms krn"
			,"    Proc mpdecision:"
			,"      CPU: 510ms usr + 2s 160ms krn"
			,"    Proc kworker/u:4:"
			,"      CPU: 10ms usr + 1s 70ms krn"
			,"    Proc kworker/u:3:"
			,"      CPU: 0ms usr + 3s 830ms krn"
			,"    Proc kworker/u:5:"
			,"      CPU: 0ms usr + 3s 240ms krn"
			,"    Proc DxDrmServerIpc:"
			,"      CPU: 10ms usr + 50ms krn"
			,"    Proc jbd2/mmcblk0p26:"
			,"      CPU: 10ms usr + 100ms krn"
			,"    Proc dmagent:"
			,"      CPU: 0ms usr + 10ms krn"
			,"    Proc kthreadd:"
			,"      CPU: 60ms usr + 0ms krn"
			,"    Proc thermald:"
			,"      CPU: 20ms usr + 180ms krn"
			,"    Proc netd:"
			,"      CPU: 40ms usr + 80ms krn"
			,"    Proc mmcqd/0:"
			,"      CPU: 0ms usr + 1s 870ms krn"
			,"    Proc kworker/u:0:"
			,"      CPU: 0ms usr + 10ms krn"
			,"    Proc kworker/0:0:"
			,"      CPU: 0ms usr + 440ms krn"
			,"    Proc htc_ebdlogd:"
			,"      CPU: 590ms usr + 2s 210ms krn"
			,"    Proc kworker/0:1:"
			,"      CPU: 0ms usr + 350ms krn"
			,"    Proc kworker/u:2:"
			,"      CPU: 0ms usr + 1s 180ms krn"
			,"    Proc kworker/0:2:"
			,"      CPU: 110ms usr + 70ms krn"
			,"    Proc kworker/u:1:"
			,"      CPU: 0ms usr + 1s 400ms krn"
			,"    Proc htcfs:"
			,"      CPU: 0ms usr + 20ms krn"
			,"    Proc bdi-default:"
			,"      CPU: 70ms usr + 0ms krn"
			,"    Proc zygote:"
			,"      CPU: 180ms usr + 150ms krn"
			,"    Proc debuggerd:"
			,"      CPU: 0ms usr + 20ms krn"
			,"    Proc flush-179:0:"
			,"      CPU: 0ms usr + 230ms krn"
			,"    Proc logcat2:"
			,"      CPU: 90ms usr + 80ms krn"
			,"    Proc ueventd:"
			,"      CPU: 10ms usr + 180ms krn"
			,"    Proc hdmid:"
			,"      CPU: 10ms usr + 60ms krn"
			,"    Proc kswapd0:"
			,"      CPU: 0ms usr + 40ms krn"
			,"    Proc sync_supers:"
			,"      CPU: 10ms usr + 0ms krn"
			,"    Proc jbd2/mmcblk0p35:"
			,"      CPU: 0ms usr + 180ms krn"
			,"    Proc installd:"
			,"      CPU: 0ms usr + 10ms krn"
			,"  #1000:"
			,"    User activity: 6 other, 22 cheek"
			,"    Wake lock show keyguard: 139ms partial (1 times) realtime"
			,"    Wake lock NetworkStats: 760ms partial (35 times) realtime"
			,"    Wake lock StayOnWhilePluggedIn Screen Dim: 162ms full (1 times) realtime"
			,"    Wake lock SyncManagerHandleSyncAlarm: 2ms partial (1 times) realtime"
			,"    Wake lock GpsLocationProvider: 1ms partial (1 times) realtime"
			,"    Wake lock sleep_broadcast: 133ms partial (1 times) realtime"
			,"    Wake lock StayOnWhilePluggedIn Partial: 54ms partial (1 times) realtime"
			,"    Wake lock BatteryServiceUpdateStats: 771ms partial (38 times) realtime"
			,"    Wake lock SmartSyncScreenOnOffTimeReceiver: 1s 161ms partial (2 times) realtime"
			,"    Wake lock HtcLockScreen:event: 71ms partial (1 times) realtime"
			,"    Wake lock AlarmManager: 16s 119ms partial (191 times) realtime"
			,"    Wake lock ConnectivityService: 57s 351ms partial (0 times) realtime"
			,"    Wake lock SyncLoopWakeLock: 2ms partial (2 times) realtime"
			,"    Wake lock ActivityManager-Sleep: 86ms partial (1 times) realtime"
			,"    TOTAL wake: 162ms full, 1m 16s 650ms partial realtime"
			,"    Sensor 4: 10m 0s 368ms realtime (0 times)"
			,"    Sensor 8: 10m 0s 297ms realtime (1 times)"
			,"    Proc time_daemon:"
			,"      CPU: 0ms usr + 50ms krn"
			,"    Proc surfaceflinger:"
			,"      CPU: 470ms usr + 890ms krn"
			,"    Proc com.android.settings:remote:"
			,"      CPU: 120ms usr + 120ms krn"
			,"      1 proc starts"
			,"    Proc servicemanager:"
			,"      CPU: 20ms usr + 120ms krn"
			,"    Apk android:"
			,"      3 wakeup alarms"
			,"    Apk com.android.settings:"
			,"      6 wakeup alarms"
			,"      Service com.android.settings.PSService:"
			,"        Created for: 33ms  uptime"
			,"        Starts: 1, launches: 1"
			,"    Apk com.htc.usage:"
			,"      Service com.htc.usage.service.UsageULogService:"
			,"        Created for: 705ms  uptime"
			,"        Starts: 2, launches: 2"
			,"  #1001:"
			,"    Wake lock RILJ: 58ms partial (3 times) realtime"
			,"    Proc rild:"
			,"      CPU: 60ms usr + 60ms krn"
			,"    Proc qmuxd:"
			,"      CPU: 30ms usr + 80ms krn"
			,"    Proc netmgrd:"
			,"      CPU: 20ms usr + 30ms krn"
			,"  #1002:"
			,"    Proc bluetoothd:"
			,"      CPU: 10ms usr + 10ms krn"
			,"    Proc dbus-daemon:"
			,"      CPU: 0ms usr + 10ms krn"
			,"  #1008:"
			,"    Proc akmd:"
			,"      CPU: 0ms usr + 10ms krn"
			,"  #1013:"
			,"    Proc mediaserver:"
			,"      CPU: 0ms usr + 90ms krn"
			,"  #1017:"
			,"    Proc keystore:"
			,"      CPU: 0ms usr + 10ms krn"
			,"  #1019:"
			,"    Proc drmserver:"
			,"      CPU: 10ms usr + 10ms krn"
			,"  #1027:"
			,"    Wake lock NfcService: 11ms partial (1 times) realtime"
			,"  #2000:"
			,"    Proc adbd:"
			,"      CPU: 0ms usr + 30ms krn"
			,"  #9987:"
			,"    (nothing executed)"
			,"  #9996:"
			,"    Proc com.htc.notes:"
			,"      CPU: 0ms usr + 0ms krn"
			,"      1 proc starts"
			,"    Proc com.htc.notes:NotesService:"
			,"      CPU: 0ms usr + 60ms krn"
			,"      1 proc starts"
			,"  #9999:"
			,"    Proc rmt_storage:"
			,"      CPU: 0ms usr + 210ms krn"
			,"  #10007:"
			,"    (nothing executed)"
			,"  #10008:"
			,"    Apk com.android.syncml.service:"
			,"      (nothing executed)"
			,"  #10009:"
			,"    Proc com.cequint.ecid:"
			,"      CPU: 10ms usr + 30ms krn"
			,"      1 proc starts"
			,"    Apk com.cequint.ecid:"
			,"      (nothing executed)"
			,"  #10015:"
			,"    (nothing executed)"
			,"  #10026:"
			,"    (nothing executed)"
			,"  #10030:"
			,"    Proc com.htc.bg:"
			,"      CPU: 0ms usr + 50ms krn"
			,"      1 proc starts"
			,"    Apk com.android.providers.calendar:"
			,"      (nothing executed)"
			,"    Apk com.htc.providers.uploads:"
			,"      (nothing executed)"
			,"  #10033:"
			,"    Wake lock Event Log Service: 5s 989ms partial (36 times) realtime"
			,"    Wake lock Checkin Handoff: 2ms partial (1 times) realtime"
			,"    Wake lock GTALK_IDLE_ALARM: 3ms partial (2 times) realtime"
			,"    Wake lock Event Log Handoff: 740ms partial (36 times) realtime"
			,"    Wake lock Checkin Service: 7ms partial (1 times) realtime"
			,"    TOTAL wake: 6s 741ms partial realtime"
			,"    Apk com.google.android.gsf:"
			,"      38 wakeup alarms"
			,"      Service com.google.android.gsf.checkin.EventLogService:"
			,"        Created for: 7s 84ms  uptime"
			,"        Starts: 36, launches: 36"
			,"      Service com.google.android.gsf.checkin.CheckinService:"
			,"        Created for: 16ms  uptime"
			,"        Starts: 1, launches: 1"
			,"  #10039:"
			,"    Apk com.android.providers.downloads:"
			,"      (nothing executed)"
			,"    Apk com.android.providers.drm:"
			,"      (nothing executed)"
			,"    Apk com.android.providers.media:"
			,"      Service com.android.providers.media.MediaScannerService:"
			,"        Created for: 232ms  uptime"
			,"        Starts: 1, launches: 1"
			,"  #10042:"
			,"    Proc com.facebook.katana:"
			,"      CPU: 80ms usr + 50ms krn"
			,"      1 proc starts"
			,"    Apk com.facebook.katana:"
			,"      2 wakeup alarms"
			,"  #10046:"
			,"    Wifi Running: 0ms (0.0%)"
			,"    Full Wifi Lock: 0ms (0.0%)"
			,"    Scan Wifi Lock: 58ms (0.0%)"
			,"    Wake lock NetworkLocationCacheUpdater: 59ms partial (2 times) realtime"
			,"    Wake lock NetworkLocationCallbackRunner: 48ms partial (2 times) realtime"
			,"    TOTAL wake: 107ms partial realtime"
			,"    Proc com.google.android.apps.maps:"
			,"      CPU: 230ms usr + 360ms krn"
			,"      1 proc starts"
			,"    Apk com.google.android.apps.maps:"
			,"      70 wakeup alarms"
			,"      Service com.google.googlenav.prefetch.android.PrefetcherService:"
			,"        Created for: 1m 40s 398ms  uptime"
			,"        Starts: 1, launches: 1"
			,"  #10051:"
			,"    (nothing executed)"
			,"  #10054:"
			,"    (nothing executed)"
			,"  #10068:"
			,"    Proc com.htc.weather.bg:"
			,"      CPU: 320ms usr + 130ms krn"
			,"      1 proc starts"
			,"    Apk com.htc.sync.provider.weather:"
			,"      Service com.htc.sync.provider.weather.SyncService:"
			,"        Created for: 6s 788ms  uptime"
			,"        Starts: 6, launches: 6"
			,"    Apk com.htc.htclocationservice:"
			,"      Service com.htc.htclocationservice.AutoSettingService:"
			,"        Created for: 30s 208ms  uptime"
			,"        Starts: 2, launches: 2"
			,"  #10072:"
			,"    Proc com.htc.htcMessageUploader:"
			,"      CPU: 0ms usr + 50ms krn"
			,"      1 proc starts"
			,"    Apk com.htc.htcMessageUploader:"
			,"      Service com.htc.htcMessageUploader.UploadMessageService:"
			,"        Created for: 31ms  uptime"
			,"        Starts: 1, launches: 1"
			,"  #10076:"
			,"    (nothing executed)"
			,"  #10133:"
			,"    Proc com.htc.android.mail:sync:"
			,"      CPU: 0ms usr + 0ms krn"
			,"      1 proc starts"
			,"    Apk com.htc.android.mail:"
			,"      Service com.htc.android.mail.mailservice.MailIntentService:"
			,"        Created for: 105ms  uptime"
			,"        Starts: 1, launches: 1"
			,"  #10135:"
			,"    Proc com.google.android.apps.uploader:"
			,"      CPU: 0ms usr + 70ms krn"
			,"      1 proc starts"
			,"  #10136:"
			,"    Proc com.android.mms:"
			,"      CPU: 20ms usr + 10ms krn"
			,"      1 proc starts"
			,"    Apk com.android.mms:"
			,"      Service com.android.mms.transaction.TransactionService:"
			,"        Created for: 368ms  uptime"
			,"        Starts: 1, launches: 1"
			,"  #10142:"
			,"    Proc com.htc.cs:"
			,"      CPU: 20ms usr + 50ms krn"
			,"      1 proc starts"
			,"  #10151:"
			,"    Proc com.google.android.apps.plus:"
			,"      CPU: 20ms usr + 60ms krn"
			,"      1 proc starts"
			,"    Apk com.google.android.apps.plus:"
			,"      Service com.google.android.picasasync.ConnectivityReceiver$AsyncService:"
			,"        Created for: 12ms  uptime"
			,"        Starts: 1, launches: 1"
			,"  #10182:"
			,"    (nothing executed)"
			,"  #10183:"
			,"    Proc com.htc.android.worldclock:"
			,"      CPU: 0ms usr + 70ms krn"
			,"      1 proc starts"
			,"  #10187:"
			,"    Wake lock IdleScreen:command: 1ms partial (1 times) realtime"
			,"    Wake lock IdleScreen:event: 167ms partial (1 times) realtime"
			,"    TOTAL wake: 168ms partial realtime"
			,"    Apk com.htc.idlescreen.shortcut:"
			,"      Service com.htc.idlescreen.shortcut.ShortcutService:"
			,"        Created for: 0ms  uptime"
			,"        Starts: 0, launches: 1"
			,"  #10192:"
			,"    (nothing executed)"
			,"  #10193:"
			,"    Apk com.att.android.arodatacollector:"
			,"      Service com.att.android.arodatacollector.main.AROCollectorTraceService:"
			,"        Created for: 0ms  uptime"
			,"        Starts: 1, launches: 1"
			,"      Service com.att.android.arodatacollector.main.AROCollectorService:"
			,"        Created for: 0ms  uptime"
			,"        Starts: 1, launches: 1"
			,""
			,"Statistics since last unplugged:"
			,"  Time on battery: 17h 41m 4s 437ms (98.7%) realtime, 11m 43s 232ms (1.1%) uptime"
			,"  Total run time: 17h 55m 35s 583ms realtime, 26m 14s 378ms uptime, "
			,"  Screen on: 10m 0s 307ms (0.9%), Input events: 0, Active phone call: 0ms (0.0%)"
			,"  Screen brightnesses: medium 10m 0s 307ms (100.0%)"
			,"  Kernel Wake lock \"qmi_564\": 67ms  (101 times) realtime"
			,"  Kernel Wake lock \"PowerManagerService\": 1m 23s 705ms  (233 times) realtime"
			,"  Kernel Wake lock \"alarm_rtc\": 27s 226ms  (134 times) realtime"
			,"  Kernel Wake lock \"smdcntl7\": 1ms  (0 times) realtime"
			,"  Kernel Wake lock \"htc_battery_8960\": 3s 480ms  (28 times) realtime"
			,"  Kernel Wake lock \"KeyEvents\": 5ms  (141 times) realtime"
			,"  Kernel Wake lock \"smdcntl0\": 16s 889ms  (85 times) realtime"
			,"  Kernel Wake lock \"smdcntl4\": 1ms  (0 times) realtime"
			,"  Kernel Wake lock \"qmuxd_500\": 18ms  (101 times) realtime"
			,"  Kernel Wake lock \"HS_PMIC\": 1ms  (0 times) realtime"
			,"  Kernel Wake lock \"power-supply\": 152ms  (29 times) realtime"
			,"  Kernel Wake lock \"radio-interface\": 2s 39ms  (2 times) realtime"
			,"  Kernel Wake lock \"smdcntl3\": 1ms  (0 times) realtime"
			,"  Kernel Wake lock \"display_mdp_idle\": 639ms  (92 times) realtime"
			,"  Kernel Wake lock \"HS_MGR\": 1ms  (0 times) realtime"
			,"  Kernel Wake lock \"vbus_lock\": 96ms  (1 times) realtime"
			,"  Kernel Wake lock \"event4-454\": 8ms  (4 times) realtime"
			,"  Kernel Wake lock \"kgsl-3d0\": 8s 334ms  (480 times) realtime"
			,"  Kernel Wake lock \"alarm\": 8s 537ms  (236 times) realtime"
			,"  Kernel Wake lock \"kgsl-2d0\": 2ms  (1 times) realtime"
			,"  Kernel Wake lock \"smdcntl6\": 1ms  (0 times) realtime"
			,"  Kernel Wake lock \"pm8921_eoc\": 6s 47ms  (0 times) realtime"
			,"  Kernel Wake lock \"smdcntl2\": 1ms  (0 times) realtime"
			,"  Kernel Wake lock \"pm8xxx_adc_wakelock\": 1s 632ms  (476 times) realtime"
			,"  Kernel Wake lock \"diagchar\": 1ms  (0 times) realtime"
			,"  Kernel Wake lock \"msm_ipc_read\": 85ms  (5 times) realtime"
			,"  Kernel Wake lock \"mmc0_detect\": 1ms  (0 times) realtime"
			,"  Kernel Wake lock \"msm_otg\": 67ms  (1 times) realtime"
			,"  Kernel Wake lock \"kgsl-2d1\": 2ms  (1 times) realtime"
			,"  Kernel Wake lock \"proximity\": 8s 117ms  (1 times) realtime"
			,"  Kernel Wake lock \"smdcntl1\": 1ms  (0 times) realtime"
			,"  Kernel Wake lock \"main\": 10m 0s 594ms  (0 times) realtime"
			,"  Kernel Wake lock \"smdcntl5\": 1ms  (0 times) realtime"
			,"  Kernel Wake lock \"port_list\": 2ms  (336 times) realtime"
			,"  Kernel Wake lock \"pm8921_unplug_ovp_fet_open_wake_lock\": 1ms  (1 times) realtime"
			,"  Total received: 0B, Total sent: 0B"
			,"  Total full wakelock time: 175ms , Total partial waklock time: 1m 23s 749ms "
			,"  Signal levels: No activity"
			,"  Signal scanning time: 0ms "
			,"  Radio types: other 17h 41m 4s 437ms (100.0%) 0x"
			,"  Radio data uptime when unplugged: 0 ms"
			,"  Wifi on: 0ms (0.0%), Wifi running: 0ms (0.0%), Bluetooth on: 0ms (0.0%)"
			," "
			,"  Device is currently plugged into power"
			,"    Last discharge cycle start level: 100"
			,"    Last discharge cycle end level: 91"
			,"    Amount discharged while screen on: 0"
			,"    Amount discharged while screen off: 9"
			," "
			,"  #0:"
			,"    Proc /init:"
			,"      CPU: 60ms usr + 920ms krn"
			,"    Proc ksoftirqd/0:"
			,"      CPU: 0ms usr + 210ms krn"
			,"    Proc vold:"
			,"      CPU: 10ms usr + 120ms krn"
			,"    Proc flush-0:17:"
			,"      CPU: 10ms usr + 0ms krn"
			,"    Proc flush-0:18:"
			,"      CPU: 10ms usr + 0ms krn"
			,"    Proc mpdecision:"
			,"      CPU: 510ms usr + 2s 160ms krn"
			,"    Proc kworker/u:4:"
			,"      CPU: 10ms usr + 1s 70ms krn"
			,"    Proc kworker/u:3:"
			,"      CPU: 0ms usr + 3s 830ms krn"
			,"    Proc kworker/u:5:"
			,"      CPU: 0ms usr + 3s 240ms krn"
			,"    Proc DxDrmServerIpc:"
			,"      CPU: 10ms usr + 50ms krn"
			,"    Proc jbd2/mmcblk0p26:"
			,"      CPU: 10ms usr + 100ms krn"
			,"    Proc dmagent:"
			,"      CPU: 0ms usr + 10ms krn"
			,"    Proc kthreadd:"
			,"      CPU: 60ms usr + 0ms krn"
			,"    Proc thermald:"
			,"      CPU: 20ms usr + 180ms krn"
			,"    Proc netd:"
			,"      CPU: 40ms usr + 80ms krn"
			,"    Proc mmcqd/0:"
			,"      CPU: 0ms usr + 1s 870ms krn"
			,"    Proc kworker/u:0:"
			,"      CPU: 0ms usr + 10ms krn"
			,"    Proc kworker/0:0:"
			,"      CPU: 0ms usr + 440ms krn"
			,"    Proc htc_ebdlogd:"
			,"      CPU: 590ms usr + 2s 210ms krn"
			,"    Proc kworker/0:1:"
			,"      CPU: 0ms usr + 350ms krn"
			,"    Proc kworker/u:2:"
			,"      CPU: 0ms usr + 1s 180ms krn"
			,"    Proc kworker/0:2:"
			,"      CPU: 110ms usr + 70ms krn"
			,"    Proc kworker/u:1:"
			,"      CPU: 0ms usr + 1s 400ms krn"
			,"    Proc htcfs:"
			,"      CPU: 0ms usr + 20ms krn"
			,"    Proc bdi-default:"
			,"      CPU: 70ms usr + 0ms krn"
			,"    Proc zygote:"
			,"      CPU: 180ms usr + 150ms krn"
			,"    Proc debuggerd:"
			,"      CPU: 0ms usr + 20ms krn"
			,"    Proc flush-179:0:"
			,"      CPU: 0ms usr + 230ms krn"
			,"    Proc logcat2:"
			,"      CPU: 90ms usr + 80ms krn"
			,"    Proc ueventd:"
			,"      CPU: 10ms usr + 180ms krn"
			,"    Proc hdmid:"
			,"      CPU: 10ms usr + 60ms krn"
			,"    Proc kswapd0:"
			,"      CPU: 0ms usr + 40ms krn"
			,"    Proc sync_supers:"
			,"      CPU: 10ms usr + 0ms krn"
			,"    Proc jbd2/mmcblk0p35:"
			,"      CPU: 0ms usr + 180ms krn"
			,"    Proc installd:"
			,"      CPU: 0ms usr + 10ms krn"
			,"  #1000:"
			,"    User activity: 6 other, 22 cheek"
			,"    Wake lock show keyguard: 139ms partial (1 times) realtime"
			,"    Wake lock NetworkStats: 760ms partial (35 times) realtime"
			,"    Wake lock StayOnWhilePluggedIn Screen Dim: 175ms full (1 times) realtime"
			,"    Wake lock SyncManagerHandleSyncAlarm: 2ms partial (1 times) realtime"
			,"    Wake lock GpsLocationProvider: 1ms partial (1 times) realtime"
			,"    Wake lock sleep_broadcast: 133ms partial (1 times) realtime"
			,"    Wake lock StayOnWhilePluggedIn Partial: 60ms partial (1 times) realtime"
			,"    Wake lock BatteryServiceUpdateStats: 776ms partial (38 times) realtime"
			,"    Wake lock SmartSyncScreenOnOffTimeReceiver: 1s 161ms partial (2 times) realtime"
			,"    Wake lock HtcLockScreen:event: 71ms partial (1 times) realtime"
			,"    Wake lock AlarmManager: 16s 119ms partial (191 times) realtime"
			,"    Wake lock ConnectivityService: 57s 356ms partial (0 times) realtime"
			,"    Wake lock SyncLoopWakeLock: 2ms partial (2 times) realtime"
			,"    Wake lock ActivityManager-Sleep: 86ms partial (1 times) realtime"
			,"    TOTAL wake: 175ms full, 1m 16s 666ms partial realtime"
			,"    Sensor 4: 10m 0s 385ms realtime (0 times)"
			,"    Sensor 8: 10m 0s 314ms realtime (1 times)"
			,"    Proc time_daemon:"
			,"      CPU: 0ms usr + 50ms krn"
			,"    Proc surfaceflinger:"
			,"      CPU: 470ms usr + 890ms krn"
			,"    Proc com.android.settings:remote:"
			,"      CPU: 120ms usr + 120ms krn"
			,"      1 proc starts"
			,"    Proc servicemanager:"
			,"      CPU: 20ms usr + 120ms krn"
			,"    Apk android:"
			,"      3 wakeup alarms"
			,"    Apk com.android.settings:"
			,"      6 wakeup alarms"
			,"      Service com.android.settings.PSService:"
			,"        Created for: 33ms  uptime"
			,"        Starts: 1, launches: 1"
			,"    Apk com.htc.usage:"
			,"      Service com.htc.usage.service.UsageULogService:"
			,"        Created for: 705ms  uptime"
			,"        Starts: 2, launches: 2"
			,"  #1001:"
			,"    Wake lock RILJ: 58ms partial (3 times) realtime"
			,"    Proc rild:"
			,"      CPU: 60ms usr + 60ms krn"
			,"    Proc qmuxd:"
			,"      CPU: 30ms usr + 80ms krn"
			,"    Proc netmgrd:"
			,"      CPU: 20ms usr + 30ms krn"
			,"  #1002:"
			,"    Proc bluetoothd:"
			,"      CPU: 10ms usr + 10ms krn"
			,"    Proc dbus-daemon:"
			,"      CPU: 0ms usr + 10ms krn"
			,"  #1008:"
			,"    Proc akmd:"
			,"      CPU: 0ms usr + 10ms krn"
			,"  #1013:"
			,"    Proc mediaserver:"
			,"      CPU: 0ms usr + 90ms krn"
			,"  #1017:"
			,"    Proc keystore:"
			,"      CPU: 0ms usr + 10ms krn"
			,"  #1019:"
			,"    Proc drmserver:"
			,"      CPU: 10ms usr + 10ms krn"
			,"  #1027:"
			,"    Wake lock NfcService: 11ms partial (1 times) realtime"
			,"  #2000:"
			,"    Proc adbd:"
			,"      CPU: 0ms usr + 30ms krn"
			,"  #9987:"
			,"    (nothing executed)"
			,"  #9996:"
			,"    Proc com.htc.notes:"
			,"      CPU: 0ms usr + 0ms krn"
			,"      1 proc starts"
			,"    Proc com.htc.notes:NotesService:"
			,"      CPU: 0ms usr + 60ms krn"
			,"      1 proc starts"
			,"  #9999:"
			,"    Proc rmt_storage:"
			,"      CPU: 0ms usr + 210ms krn"
			,"  #10007:"
			,"    (nothing executed)"
			,"  #10008:"
			,"    Apk com.android.syncml.service:"
			,"      (nothing executed)"
			,"  #10009:"
			,"    Proc com.cequint.ecid:"
			,"      CPU: 10ms usr + 30ms krn"
			,"      1 proc starts"
			,"    Apk com.cequint.ecid:"
			,"      (nothing executed)"
			,"  #10015:"
			,"    (nothing executed)"
			,"  #10026:"
			,"    (nothing executed)"
			,"  #10030:"
			,"    Proc com.htc.bg:"
			,"      CPU: 0ms usr + 50ms krn"
			,"      1 proc starts"
			,"    Apk com.android.providers.calendar:"
			,"      (nothing executed)"
			,"    Apk com.htc.providers.uploads:"
			,"      (nothing executed)"
			,"  #10033:"
			,"    Wake lock Event Log Service: 5s 989ms partial (36 times) realtime"
			,"    Wake lock Checkin Handoff: 2ms partial (1 times) realtime"
			,"    Wake lock GTALK_IDLE_ALARM: 3ms partial (2 times) realtime"
			,"    Wake lock Event Log Handoff: 740ms partial (36 times) realtime"
			,"    Wake lock Checkin Service: 7ms partial (1 times) realtime"
			,"    TOTAL wake: 6s 741ms partial realtime"
			,"    Apk com.google.android.gsf:"
			,"      38 wakeup alarms"
			,"      Service com.google.android.gsf.checkin.EventLogService:"
			,"        Created for: 7s 84ms  uptime"
			,"        Starts: 36, launches: 36"
			,"      Service com.google.android.gsf.checkin.CheckinService:"
			,"        Created for: 16ms  uptime"
			,"        Starts: 1, launches: 1"
			,"  #10039:"
			,"    Apk com.android.providers.downloads:"
			,"      (nothing executed)"
			,"    Apk com.android.providers.drm:"
			,"      (nothing executed)"
			,"    Apk com.android.providers.media:"
			,"      Service com.android.providers.media.MediaScannerService:"
			,"        Created for: 232ms  uptime"
			,"        Starts: 1, launches: 1"
			,"  #10042:"
			,"    Proc com.facebook.katana:"
			,"      CPU: 80ms usr + 50ms krn"
			,"      1 proc starts"
			,"    Apk com.facebook.katana:"
			,"      2 wakeup alarms"
			,"  #10046:"
			,"    Wifi Running: 0ms (0.0%)"
			,"    Full Wifi Lock: 0ms (0.0%)"
			,"    Scan Wifi Lock: 58ms (0.0%)"
			,"    Wake lock NetworkLocationCacheUpdater: 59ms partial (2 times) realtime"
			,"    Wake lock NetworkLocationCallbackRunner: 48ms partial (2 times) realtime"
			,"    TOTAL wake: 107ms partial realtime"
			,"    Proc com.google.android.apps.maps:"
			,"      CPU: 230ms usr + 360ms krn"
			,"      1 proc starts"
			,"    Apk com.google.android.apps.maps:"
			,"      70 wakeup alarms"
			,"      Service com.google.googlenav.prefetch.android.PrefetcherService:"
			,"        Created for: 1m 40s 398ms  uptime"
			,"        Starts: 1, launches: 1"
			,"  #10051:"
			,"    (nothing executed)"
			,"  #10054:"
			,"    (nothing executed)"
			,"  #10068:"
			,"    Proc com.htc.weather.bg:"
			,"      CPU: 320ms usr + 130ms krn"
			,"      1 proc starts"
			,"    Apk com.htc.sync.provider.weather:"
			,"      Service com.htc.sync.provider.weather.SyncService:"
			,"        Created for: 6s 788ms  uptime"
			,"        Starts: 6, launches: 6"
			,"    Apk com.htc.htclocationservice:"
			,"      Service com.htc.htclocationservice.AutoSettingService:"
			,"        Created for: 30s 208ms  uptime"
			,"        Starts: 2, launches: 2"
			,"  #10072:"
			,"    Proc com.htc.htcMessageUploader:"
			,"      CPU: 0ms usr + 50ms krn"
			,"      1 proc starts"
			,"    Apk com.htc.htcMessageUploader:"
			,"      Service com.htc.htcMessageUploader.UploadMessageService:"
			,"        Created for: 31ms  uptime"
			,"        Starts: 1, launches: 1"
			,"  #10076:"
			,"    (nothing executed)"
			,"  #10133:"
			,"    Proc com.htc.android.mail:sync:"
			,"      CPU: 0ms usr + 0ms krn"
			,"      1 proc starts"
			,"    Apk com.htc.android.mail:"
			,"      Service com.htc.android.mail.mailservice.MailIntentService:"
			,"        Created for: 105ms  uptime"
			,"        Starts: 1, launches: 1"
			,"  #10135:"
			,"    Proc com.google.android.apps.uploader:"
			,"      CPU: 0ms usr + 70ms krn"
			,"      1 proc starts"
			,"  #10136:"
			,"    Proc com.android.mms:"
			,"      CPU: 20ms usr + 10ms krn"
			,"      1 proc starts"
			,"    Apk com.android.mms:"
			,"      Service com.android.mms.transaction.TransactionService:"
			,"        Created for: 368ms  uptime"
			,"        Starts: 1, launches: 1"
			,"  #10142:"
			,"    Proc com.htc.cs:"
			,"      CPU: 20ms usr + 50ms krn"
			,"      1 proc starts"
			,"  #10151:"
			,"    Proc com.google.android.apps.plus:"
			,"      CPU: 20ms usr + 60ms krn"
			,"      1 proc starts"
			,"    Apk com.google.android.apps.plus:"
			,"      Service com.google.android.picasasync.ConnectivityReceiver$AsyncService:"
			,"        Created for: 12ms  uptime"
			,"        Starts: 1, launches: 1"
			,"  #10182:"
			,"    (nothing executed)"
			,"  #10183:"
			,"    Proc com.htc.android.worldclock:"
			,"      CPU: 0ms usr + 70ms krn"
			,"      1 proc starts"
			,"  #10187:"
			,"    Wake lock IdleScreen:command: 1ms partial (1 times) realtime"
			,"    Wake lock IdleScreen:event: 167ms partial (1 times) realtime"
			,"    TOTAL wake: 168ms partial realtime"
			,"    Apk com.htc.idlescreen.shortcut:"
			,"      Service com.htc.idlescreen.shortcut.ShortcutService:"
			,"        Created for: 0ms  uptime"
			,"        Starts: 0, launches: 1"
			,"  #10192:"
			,"    (nothing executed)"
			,"  #10193:"
			,"    Apk com.att.android.arodatacollector:"
			,"      Service com.att.android.arodatacollector.main.AROCollectorTraceService:"
			,"        Created for: 0ms  uptime"
			,"        Starts: 1, launches: 1"
			,"      Service com.att.android.arodatacollector.main.AROCollectorService:"
			,"        Created for: 0ms  uptime"
			,"        Starts: 1, launches: 1"
		};  
	}       
}           
